runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  NEXTAUTH_URL: "https://growthbdm.com"
  GOOGLE_ID: "454219563663-mt8b4dlvkfd48uflie0njsjodhc01jgo.apps.googleusercontent.com"
  GOOGLE_SECRET: "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"
  NEXTAUTH_SECRET: "growth_bdm_scheduler_secret_key_2024"
  NODE_ENV: "production"
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/growthbdm?schema=public"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "de4dpzh9c"
  CLOUDINARY_API_KEY: "624144452112574"
  CLOUDINARY_API_SECRET: "Tw1jSlROHPsi82nVCjkLr9zcaAY"

handlers:
  - url: /.*
    script: auto
    secure: always

build_env_variables:
  NEXT_TELEMETRY_DISABLED: "1"
